### ISSUE TITLE
Create LIST command

### ISSUE THREAD

**Issue by wdanfort** [airq-dev/hazebot#102]
list subscription zipcodes -- what is the mechanism for unsubscribing? U 94118? etc.?

**Comment by ianhoffman** [comment]
Right now you can only sub to one zipcode at once, and whenever you change your sub the old one goes away. So we should be good here.

**Comment by wdanfort** [comment]
Aaaah perfect, when you are moving this fast, hard to keep up!

**Comment by ianhoffman** [comment]
Haha yeah. I think this is a good direction! It will be important to gather feedback tho since this is a big big change.
