### ISSUE TITLE
Show 3 closest areas with better AQI regardless of distance

### ISSUE THREAD

**Issue by ianhoffman** [airq-dev/hazebot#108]
for better air quality nearby, instead of saying there's nothing better would be more helpful to share the three closed areas with better air quality, regardless of distance (so you know how bad it really is)

**Comment by emilypstabler** [comment]
Might be helpful to include distance (mi) of each area from original Zip, in case user wants to know how far poor air quality extends

**Comment by ianhoffman** [comment]
We originally had this and removed it to keep things short, but I do like it more now that we've separated recommendations into their own menu item. I agree we should do this.

**Comment by ianhoffman** [comment]
I also think this improvement is done per a change I pushed today (not the change you suggest @emilypstabler , but the original enhancement). I'll create a new issue to track work on showing distance and close this one out.
