### ISSUE TITLE
Be more permissive in what commands we accept

### ISSUE THREAD

**Issue by ianhoffman** [airq-dev/hazebot#116]
From Slack:

"Might want to account for punctuation in the menu options, if we’re sticking w/ number options? It’s not totally clear if “.” is required after the number from the instructions, but if you input “1.” you’re told option is unrecognizable"

We should accept both "1." and "1" as a valid command.

**Comment by emjgreen** [comment]
Should we also allow "1)" as a valid command, along with the ones mention above?

**Comment by ianhoffman** [comment]
Sure! I doubt many people will do that when prompted with `1.`, but it can't hurt.
