### ISSUE TITLE
Surface distances (in miles) in recommendations

### ISSUE THREAD

**Issue by ianhoffman** [airq-dev/hazebot#124]
It would be useful to know how far away places with good AQI are. We could surface this information (in mi) when giving recommendations, since we already calculate it when determining the nearest zipcodes. We'd just need to convert km to mi and add it to the copy.

**Comment by emjgreen** [comment]
I'll tackle this!

**Comment by ianhoffman** [comment]
Awesome!

**Comment by emjgreen** [comment]
Done in https://github.com/airq-dev/hazebot/pull/129
