### ISSUE TITLE
Store phone numbers (or hashes of them)

### ISSUE THREAD

**Issue by deanlyoung** [airq-dev/hazebot#59]
In order to recognize a return user and not have to require zip code every time (plus added benefit of accepting new "commands").

**Comment by ianhoffman** [comment]
Yeah, for sure. We actually already do this: https://github.com/airq-dev/airq/blob/master/app/airq/models/requests.py#L13

I've been thinking about commands. You should def be able to send something and get the data for the last zipcode you entered.

**Comment by deanlyoung** [comment]
Awesome. I couldn't quite follow along, but it's not storing phone numbers in plaintext, is it?

**Comment by ianhoffman** [comment]
It is. Should it not be? In my experience emails aren’t considered PII but maybe phone numbers are?

**Comment by ianhoffman** [comment]
Or I guess that’s wrong — emails are PII but they’re OK to keep unhashed in a database in most cases.

**Comment by deanlyoung** [comment]
tbh... I don't really know. Just seems like an unnecessary risk to safeguard them (or, I don't know, maybe it is the only way). Is there any way to protect them, like hashing a password, but still making it useable when integrating with, for example, Twilio?

**Comment by ianhoffman** [comment]
We could look into using "encryption at rest" in our Postgres instance: https://brightlineit.com/encryption-at-rest-important-business/

I don't think this is really a high prio, though. I've seen emails stored unhashed at much larger operations than this. From a security perspective, as long as we aren't dealing with government/HIPAA stuff, I think it's fine. We're already running the DB in a VPC, so breaking into it isn't as simple as just having the password — you'd need to get into the VPC too, which is currently locked down to only certain IPs.
